EntityFrameworkProject/Models/BaseEntity.cs
namespace EntityFrameworkProject.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; } = false;
    }
}

EntityFrameworkProject/Models/Category.cs
using System.Collections.Generic;

namespace EntityFrameworkProject.Models
{
    public class Category : BaseEntity
    {
        public string Name { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

EntityFrameworkProject/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EntityFrameworkProject.Models
{
    public class Product : BaseEntity
    {
        public string Title { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal Price { get; set; }
        public string Description { get; set; }
        public DateTime CreateDate { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public ICollection<ProductImage> ProductImages { get; set; }

    }
}

EntityFrameworkProject/Models/ProductImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Models
{
    public class ProductImage:BaseEntity
    {
        public string Image { get; set; }
        public bool IsMain { get; set; } = false;
        public int ProductId { get; set; }
        public Product Product { get; set; }

    }
}

EntityFrameworkProject/Models/Slider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Models
{
    public class Slider : BaseEntity
    {
        public string  Image { get; set; }
    }
}

EntityFrameworkProject/Models/SliderDetail.cs
namespace EntityFrameworkProject.Models
{
    public class SliderDetail : BaseEntity
    {
        public string Header { get; set; }
        public string Description { get; set; }
        public string SignImage { get; set; }
    }
}

EntityFrameworkProject/ViewModels/BasketVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.ViewModels
{
    public class BasketVM
    {
        public int Id { get; set; }
        public int Count { get; set; }
    }
}

EntityFrameworkProject/ViewModels/HomeVM.cs
using EntityFrameworkProject.Models;
using System.Collections.Generic;

namespace EntityFrameworkProject.ViewModels
{
    public class HomeVM
    {
        public IEnumerable<Slider> Sliders { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Product> Products { get; set; }
        public SliderDetail SliderDetail { get; set; }
    }
}

EntityFrameworkProject/Areas/AdminArea/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

EntityFrameworkProject/Areas/AdminArea/Controllers/SliderController.cs
using EntityFrameworkProject.Data;
using EntityFrameworkProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;

        public SliderController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Slider> sliders = await _context.Sliders.Where(m=>!m.IsDeleted).ToListAsync();
            return View(sliders);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
    }
}

EntityFrameworkProject/Controllers/HomeController.cs
using EntityFrameworkProject.Data;
using EntityFrameworkProject.Models;
using EntityFrameworkProject.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            HttpContext.Session.SetString("name", "esqin");
            Response.Cookies.Append("surname", "Ceferli");

            IEnumerable<Slider> sliders = await _context.Sliders.ToListAsync();
            SliderDetail sliderDetail = await _context.SliderDetails.FirstOrDefaultAsync();
            IEnumerable<Category> categories = await _context.Categories.Where(m => m.IsDeleted == false).ToListAsync();
            IEnumerable<Product> products = await _context.Products
                .Where(m => m.IsDeleted == false)
                .Include(m => m.Category)
                .Include(m => m.ProductImages).Take(4).ToListAsync();


            HomeVM model = new HomeVM
            {
                Sliders = sliders,
                SliderDetail = sliderDetail,
                Categories = categories,
                Products = products
            };

            return View(model);
        }

        public IActionResult Test()
        {
            var sessionData = HttpContext.Session.GetString("name");
            var cookieData = Request.Cookies["surname"];
            return Json(sessionData + " " + cookieData);
        }

        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            //var dbProduct = _context.Products.FirstOrDefaultAsync();
            var dbProduct = await _context.Products.FindAsync(id);

            if (dbProduct == null)
            {
                return BadRequest();
            }

            List<BasketVM> baskets;

            if (Request.Cookies["basket"] != null)
            {
                baskets = JsonConvert.DeserializeObject<List<BasketVM>>(Request.Cookies["basket"]);
            }
            else
            {
                baskets = new List<BasketVM>();
            }

            var basketCount = baskets.Count;

            var isExist = baskets.Find(m => m.Id == id);

            if (isExist != null)
            {

                isExist.Count++;
            }
            else
            {
                baskets.Add(new BasketVM
                {
                    Id = dbProduct.Id,
                    Count = basketCount
                }); 
            }







            Response.Cookies.Append("basket", JsonConvert.SerializeObject(baskets));
            return RedirectToAction("Index");
        }
    }
}

EntityFrameworkProject/Controllers/ProductController.cs
using EntityFrameworkProject.Data;
using EntityFrameworkProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EntityFrameworkProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;
        public ProductController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.count = await _context.Products.Where(m => !m.IsDeleted).CountAsync();
            IEnumerable<Product> products = await _context.Products.Where(m => !m.IsDeleted).Include(m => m.ProductImages).Take(4).OrderBy(m => m.Id).ToListAsync();
            return View(products);
        }

        ///product/loadmore

        public async Task<IActionResult> LoadMore(int skip)
        {
            IEnumerable<Product> products = await _context.Products.Where(m => !m.IsDeleted).Include(m=>m.Category).Include(m=>m.ProductImages).Skip(skip).Take(4).ToListAsync();

            return PartialView("_ProductsPartial", products);
        }
    }
}

EntityFrameworkProject/Areas/AdminArea/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="main-panel">
    <h3>Admin dashboard</h3>
</div>

EntityFrameworkProject/Areas/AdminArea/Views/Slider/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<div class="container-fluid mx-5 my-3">
    <h3>Slider image</h3>
    <form>
        <div class="form-group">
            <input type="file" multiple class="form-control">
        </div>
        <a class="btn btn-primary" asp-controller="Slider" asp-action="Index">Back</a>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

EntityFrameworkProject/Areas/AdminArea/Views/Slider/Index.cshtml
@model IEnumerable<Slider>
@{
    ViewData["Title"] = "Index";
}

<div class="container-fluid my-3 mx-3">
    <div class="table-responsive pt-3">
        <div class="create-btn mb-3">
            <a asp-area="AdminArea" asp-controller="Slider" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i></a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                    <th style="text-align: center;">
                        Settings
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img  src="~/img/@item.Image" alt="slider" />
                        </td>
                        <td style="text-align: center;">
                            <button type="button" class="btn btn-info"><i class="mdi mdi-information mx-0"></i></button>
                            <button type="button" class="btn btn-primary"><i class="mdi mdi-table-edit"></i></button>
                            <button type="button" class="btn btn-danger"><i class="mdi mdi-delete-forever"></i></button>
                        </td>
                    </tr>

                }

            </tbody>
        </table>
    </div>
</div>

EntityFrameworkProject/Views/Product/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <input type="hidden" id="product-count" value="@ViewBag.count" />
    <h1>Products</h1>
    <div class="row my-5" id="parent-products">
        <partial name="_ProductsPartial" />
    </div>

    <div class="show-more d-flex justify-content-center my-2 mb-2 w-100">
        <button class="btn btn-primary">Show more ...</button>
    </div>
</div>

EntityFrameworkProject/Views/Shared/_OtherLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <header>Header</header>
        @RenderBody()
        <footer>Footer</footer>
    </div>
</body>
</html>

EntityFrameworkProject/Views/Shared/_ProductsPartial.cshtml
@model IEnumerable<Product>

@foreach (var product in Model)
{
    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
        <div class="product-item text-center" data-id="@product.CategoryId">
            <div class="img">
                <a href="">
                    <img src="~/img/@product.ProductImages.FirstOrDefault(m=>m.IsMain)?.Image" class="img-fluid" alt="">
                </a>
            </div>
            <div class="title mt-3">
                <h6>@product.Title</h6>
            </div>
            <div class="price">
                <span class="text-black-50"><a asp-controller="Home" asp-action="AddBasket" asp-route-id="@product.Id">add to cart </a> </span>
                <span class="text-black-50">$@product.Price</span>
            </div>
        </div>
    </div>
}